#Requires -RunAsAdministrator
<#
CatCam installer. Run from an elevated PowerShell:
    powershell -ExecutionPolicy Bypass -File installer\install.ps1

What it does, in order:
  1. Checks the Windows binaries exist (build them with windows\build.bat).
  2. Ensures VB-Audio Virtual Cable is present for the microphone path:
     downloads the official pack from vb-audio.com if missing (their
     installer GUI opens, click "Install Driver"). VB-Cable is proprietary
     donationware and is deliberately NOT bundled with CatCam; skip with
     -SkipAudio if you only want video.
  3. Grants the Frame Server (LOCAL SERVICE) read access to the DLL and
     registers the COM media source.
  4. Creates the "CatCam" logon task (elevated) running catcam-boot.bat,
     and starts it now.
adb is expected at %USERPROFILE%\android-sdk\platform-tools\adb.exe or
pass -AdbPath; pass -Serial only if several USB devices are attached.
Both are written to windows\catcam.env.bat (machine-local, git-ignored),
which every operations script loads via catcam-env.bat.
#>
param(
    [switch]$SkipAudio,
    [string]$AdbPath = "$env:USERPROFILE\android-sdk\platform-tools\adb.exe",
    [string]$Serial = ""
)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$win  = Join-Path $root 'windows'

Write-Host "== CatCam install from $root"

# 1. Binaries
$need = @('CatCamHost.exe', 'CatCamSource.dll', 'CatCamTray.exe')
$missing = $need | Where-Object { -not (Test-Path (Join-Path $win $_)) }
if ($missing) {
    Write-Host "Missing binaries: $($missing -join ', ')" -ForegroundColor Yellow
    Write-Host "Build them first: windows\build.bat (VS2022 + Windows 11 SDK)."
    exit 1
}

# 2. VB-Cable (microphone endpoint)
if (-not $SkipAudio) {
    $cable = Get-CimInstance Win32_SoundDevice -ErrorAction SilentlyContinue |
             Where-Object { $_.Name -match 'VB-Audio' }
    if ($cable) {
        Write-Host "VB-Cable already installed: $($cable[0].Name)"
    } else {
        Write-Host "VB-Cable not found: fetching from vb-audio.com (official site)..."
        $zip = Join-Path $env:TEMP 'vbcable.zip'
        $dst = Join-Path $env:TEMP 'vbcable'
        $got = $false
        foreach ($u in @('https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack45.zip',
                         'https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack43.zip')) {
            try { Invoke-WebRequest $u -OutFile $zip -UseBasicParsing; $got = $true; break } catch {}
        }
        if (-not $got) {
            Write-Host "Download failed: opening the official page, install manually, then re-run." -ForegroundColor Yellow
            Start-Process 'https://vb-audio.com/Cable/'
            exit 1
        }
        Expand-Archive $zip $dst -Force
        $setup = Get-ChildItem $dst -Recurse -Filter 'VBCABLE_Setup_x64.exe' | Select-Object -First 1
        if (-not $setup) { throw "VBCABLE_Setup_x64.exe not found in the pack" }
        Write-Host "VB-Cable installer opening: click 'Install Driver'. A reboot may be requested."
        Start-Process $setup.FullName -Wait
    }
}

# 3. DLL access + COM registration (Frame Server runs as LOCAL SERVICE and
#    must be able to load the DLL from this directory).
icacls (Join-Path $win 'CatCamSource.dll') /grant 'NT AUTHORITY\LOCAL SERVICE:RX' | Out-Null
& regsvr32 /s (Join-Path $win 'CatCamSource.dll')
Write-Host "COM media source registered."

# 4. Machine-local settings for the operations scripts (only written when
#    they differ from the portable defaults).
$envBat = Join-Path $win 'catcam.env.bat'
$lines = @('@echo off', 'REM Generated by installer\install.ps1; safe to edit or delete.')
if ($AdbPath -ne "$env:USERPROFILE\android-sdk\platform-tools\adb.exe") { $lines += "set CATCAM_ADB=$AdbPath" }
if ($Serial) { $lines += "set CATCAM_SERIAL=$Serial" }
if ($lines.Count -gt 2) {
    Set-Content $envBat ($lines -join "`r`n")
    Write-Host "Wrote $envBat"
}

# 5. Logon task + start now
$boot = Join-Path $win 'catcam-boot.bat'
schtasks /create /tn CatCam /sc onlogon /rl highest /tr "`"$boot`"" /f | Out-Null
Write-Host "Logon task 'CatCam' created."

if (Test-Path $AdbPath) {
    Write-Host "adb found. Devices:"
    & $AdbPath devices
    Write-Host "On the device: enable USB debugging, authorize this PC, and set"
    Write-Host "Developer options > Default USB configuration = Charging only."
} else {
    Write-Host "adb NOT found at $AdbPath (needed for USB transport and remote control)." -ForegroundColor Yellow
}

Start-Process $boot
Write-Host ""
Write-Host "Done. Pick 'CatCam' as camera and 'CABLE Output (VB-Audio Virtual"
Write-Host "Cable)' as microphone in your calling app. The tray icon's dot:"
Write-Host "green = streaming, yellow = waiting for device, red = host down."
