# USB cable mode: fetch Google platform-tools (adb) into the install dir and
# point the operations scripts at it via catcam.env.bat. Wi-Fi mode does not
# need any of this. Invoked by CatCamSetup when the USB task is selected.
param([string]$InstallDir = (Split-Path $PSScriptRoot -Parent))
$zip = Join-Path $env:TEMP 'platform-tools.zip'
try {
    Invoke-WebRequest 'https://dl.google.com/android/repository/platform-tools-latest-windows.zip' `
        -OutFile $zip -UseBasicParsing
} catch {
    Write-Host "platform-tools download failed; USB mode can be set up later."
    exit 0
}
Expand-Archive $zip $InstallDir -Force   # creates $InstallDir\platform-tools
$adb = Join-Path $InstallDir 'platform-tools\adb.exe'
Set-Content (Join-Path $InstallDir 'catcam.env.bat') @(
    '@echo off',
    'REM Generated by CatCamSetup; safe to edit or delete.',
    "set CATCAM_ADB=$adb"
)
Write-Host "adb installed at $adb. On the tablet: enable Developer options and USB debugging."
